### ISSUE TITLE
RAMAnimatedTabBarController cannot work correctly with Objective-C code?

### ISSUE THREAD

**Issue by gcbinsp** [Ramotion/animated-tab-bar#10]
In my project, except RAMAnimatedTabBarController, all of the code is Objective-C. When I tap the tab bar item, the deselectItem does not invoke the deselect animation, it keeps the selected status always.

**Comment by gcbinsp** [comment]
I found the solution by adding textSelectedColor and iconSelectedColor to Bounce Animation on the storyboard.
I have to say the document of this project is so poor!

**Comment by Kowaio** [comment]
Hi @gcbinsp,

I'm currently struggling while trying to use this lib in my obj-c project. I can't find a solution for the project to link using RAMAnimated classes programmatically.

I'm just trying to replace my MainViewController which is a subclass of UITabBarController with an RAMAnimatedTabBarController but the project won't build/link saying that RAMAnimatedTabBarController doesn't exist. I've imported my "Project-Swift.h" header too. While jumping to the definition of RAMAnimatedTabBarController, Xcode goes there without a blink, so that's weird too.

If I try to only use this lib in the storyboard, it seems to build/link correctly but I really need to use it programmatically with my own class so I'm hitting a wall here.

If you have any idea or feedback about that, I'd be very thankful.

**Comment by thidayatullah** [comment]
I'm having the same problem with @Kowaio 
I want to use this library in my ObjC project without using story board.

**Comment by thidayatullah** [comment]
And now I'm looking at this library instead : [animated-tab-bar](https://github.com/polobymulberry/animated-tab-bar-Objective-C)
