### ISSUE TITLE
UITabBarControllerDelegate Doesn't work

### ISSUE THREAD

**Issue by aalzanki** [Ramotion/animated-tab-bar#42]
You can't delegate RAMAnimatedTabBarController.

**Comment by cdf1982** [comment]
+1, I used to call `tabBarController(tabBarController: UITabBarController, didSelectViewController viewController: UIViewController)` and it worked fine before, but since I adopted RAMAnimatedTabBarController this method isn't called anymore; I tried changing the type in the function name, but didn't work... any suggestions?
